# Generated by Django 3.2 on 2021-12-27 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_shopuser_activation_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authapp.shopuser')),
                ('tagline', models.CharField(blank=True, max_length=128, verbose_name='tags')),
                ('about_me', models.TextField(blank=True, max_length=512)),
                ('gender', models.CharField(blank=True, choices=[('M', 'male'), ('W', 'female')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='age',
            field=models.PositiveIntegerField(default=18, null=True),
        ),
    ]
